### ISSUE TITLE
1.18.2 version of the mod

### ISSUE THREAD

**Issue by BluEagleOfficial** [Camotoy/BedrockSkinUtility#10]
I know it maybe can be a pain in the ass. But if you can or already have a 1.18 version of the mod it would help me enourmously. Thanks for your time

**Comment by Camotoy** [comment]
While I don't plan on updating 1.18.2 support, version 1.2.1 should support 1.18.x.

**Comment by BluEagleOfficial** [comment]
Thank you, where can i find an download tho?

**Comment by Camotoy** [comment]
See Modrinth or GitHub Releases here.

**Comment by BluEagleOfficial** [comment]
I needed to press on the blue text to see all releases. Now i feel kinda dumb, thank you for your time and for fast response
