### ISSUE TITLE
Error in minecraft 1.19.3 (fabric)

### ISSUE THREAD

**Issue by nakanotti** [Camotoy/BedrockSkinUtility#11]
Error message:
```
Internal Exception: java.lang.NoSuchMethodError:
'net.minecraft.class_2703$class_5893 
net.minecraft.class_2703.method_11723()'
```

fabric information:
- minecraft_version=1.19.3
- yarn_mappings=1.19.3+build.3
- loader_version=0.14.11
- fabric_version=0.69.1+1.19.3

**Comment by nakanotti** [comment]
https://github.com/Camotoy/BedrockSkinUtility/blob/e5d9aedc850b69011bf961262fd6f4f83544b25c/src/main/java/net/camotoy/bedrockskinutility/client/mixin/ClientPlayNetworkHandlerMixin.java#L34

https://maven.fabricmc.net/docs/yarn-1.19.3+build.3/net/minecraft/network/packet/s2c/play/PlayerListS2CPacket.html#getActions()

Maybe because getAction changed?

**Comment by Camotoy** [comment]
I have pending changes for 1.19.3 I just need to test and deploy.

**Comment by nakanotti** [comment]
Thank you for your commit.
`BedrockSkinUtility-1.4.0-SNAPSHOT.jar` can be started without problems.
