### ISSUE TITLE
fabric capes mod resupport

### ISSUE THREAD

**Issue by TheAlarm117571** [Camotoy/BedrockSkinUtility#5]
In the latest version of Minecraft 1.18.1 the mod doesn't work with the fabric capes mod anymore

Mods:
![mods](https://user-images.githubusercontent.com/56905561/147380280-2e5fc775-345e-4e38-a635-ee0c9fe4552e.PNG)

log:
https://paste.ee/p/g4D9w

**Comment by Camotoy** [comment]
Fixed.
