### ISSUE TITLE
HD skins render incorrectly

### ISSUE THREAD

**Issue by DB20-official** [Camotoy/BedrockSkinUtility#9]
### Description
I have recently started implementing Bedrock skin support into my server. And during my testing, I discovered HD skins from Bedrock players will not render correctly in-game. It does not affect the head that shows up in the player list though. If there's anything I am doing wrong, let me know.

### Behaviors
**Expected behavior:** The skin shows up correctly like how the skin would show up on Bedrock.
**Actual behavior:** The skin appears broken, as if the client is only reading a quarter of the skin file instead of the whole image.

### Image proof
![2022-07-04_18 39 27](https://user-images.githubusercontent.com/26073967/177222632-2dba2628-5ac8-4af8-9a78-393345f833ee.png)

### Testing environment
Minecraft version: 1.18.2
Mod loader: Fabric 0.14.3
Mod version: 1.2.1 (happens on 1.3.0 on 1.19 as well)
Mods loaded: Fabric API, ModMenu, Cloth Config, **BedrockSkinUtility**

**Comment by Camotoy** [comment]
Can you share what skin pack you're using for this skin?

**Comment by DB20-official** [comment]
It's not a skin pack. It's a custom skin made by myself that is twice the resolution of a regular Minecraft skin. No actual 3D geometry. The skin file is 128x128 pixels.

**Comment by Camotoy** [comment]
Are you able to share the skin or another skin with the same issue? Is it as easy as applying it like a classic, Java-supported skin? I’m unfamiliar in this territory.

**Comment by DB20-official** [comment]
There aren't many individual skins I can share. Applying those skins on Bedrock is as easy as applying a classic, Java supported skin. However, due to them being double the resolution, they only work on Bedrock. I tested other skin packs (ones from the Marketplace) that feature HD skins with mixed results. Some work while others don't. Ones with custom geometry break while others work but show the wrong model (Alex skin as Steve skin).

**Comment by DB20-official** [comment]
It turns out some other skin packs with HD skins break in weirder ways, very similar to how custom HD player skins break. When you import a custom skin, ensure the skin file is 128x128 pixels, exactly double the size of a normal-sized skin. I also tested the mod on 1.19 and 1.19.1 to no effect. If you need a skin to reproduce the bug, let me know.

**Comment by Camotoy** [comment]
A skin that the bug happens with would be helpful just to make sure I have an exact one.

**Comment by DB20-official** [comment]
Can't exactly give the skin, but here is a test skin that was pre-created with Blockbench in a "32x" resolution. Should be the correct resolution for Bedrock to use. Every HD skin like this I tried out so far has bugged, with the exception of some Marketplace skins.
![test](https://user-images.githubusercontent.com/26073967/182968959-b768f5bc-ebd2-492c-b706-f800ac2ed884.png)
Software used to pre-generate the skin: Blockbench 4.3.1 (Desktop client)
_If you're unable to use the skin in Bedrock, let me know._

**Comment by DB20-official** [comment]
The bug I'm currently getting is with a custom HD skin with a slim model (including the one in the previous comment). Just to make sure it wasn't specific to slim skins, I tried it with a classic model as well. Exactly the same as last time. Only using 1/4 of the skin image instead of the whole thing on the model, and rendering its head just fine in the player (TAB) list.

![image](https://user-images.githubusercontent.com/26073967/188535028-afac3479-0247-4444-ac14-a0956efbce0e.png)

Have you been able to reproduce the bug yet? This time, it was tested with 1.3.0 of the mod on 1.19.2.
